# Generated by Django 3.1.2 on 2020-10-16 04:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('titulo', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID Unico del VideoJuego', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Ingrese una breve descripcion del VideoJuego', max_length=1000)),
                ('creador', models.CharField(max_length=200)),
                ('tipogame', models.CharField(max_length=200)),
            ],
        ),
    ]
